<?php
    echo "
    <header>
    <nav id=\"nav\">
        <a class=\"link\" href=\"index.php\">Home</a>
        <a class=\"link\" href=\"jobs.php\">Job Description</a>
        <a class=\"link\" href=\"about.php\">Group Detail</a>
        <a class=\"link\" href=\"enhancement.php\">Group's enhancements</a>
        <a class=\"link\" href=\"apply.php\">Apply now</a>
    </nav>
    </header>
    ";
?>
