<?php
    echo "
    <a href=\"index.php\">
		<img id=\"logo\" src=\"images/logo-Copy.png\" alt=\"MTD Tech Corporate Offical Logo\">
	</a>
	<h1 id=\"welcome\">Welcome to our company</h1>
    <header>
    <nav id=\"nav\">
        <a class=\"link\" href=\"index.php\">Home</a>
        <a class=\"link\" href=\"jobs.php\">Job Description</a>
        <a class=\"link\" href=\"about.php\">Group Detail</a>
        <a class=\"link\" href=\"enhancement.php\">Group's enhancements</a>
        <a class=\"link\" href=\"apply.php\">Apply now</a>
        <a class=\"link\" href=\"login.php\">Manager page</a>
    </nav>
    </header>
    ";
?>
